[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/blog"
  status = 302
  force = true

[[redirects]]
  from = "https://itaydafna-dev.netlify.app/*"
  to = "https://www.itaydafna.dev/:splat"
  status = 301
  force = true