[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/blog"
  status = 302
  force = true

[[redirects]]
  https://itaydafna-dev.netlify.app/* https://www.itaydafna.dev/:splat 302!